### ISSUE TITLE
npm error when unpacking/running the app

### ISSUE THREAD

**Issue by ialexander26** [IBM/build-blockchain-insurance-app#31]
<img width="673" alt="screen shot 2018-05-30 at 12 10 58 am" src="https://user-images.githubusercontent.com/15055888/40732119-d59671a8-63ef-11e8-80af-28ccdc0d62c5.png">

**Comment by subbaraok** [comment]
I see similar output when using Ubuntu Host .. After making the change as in my comment for issue #24 App is stable ...

**Comment by ialexander26** [comment]
Thanks, but I'm not sure I understand how to implement the changes.  Can you please explain? 

Thanks again.

**Comment by ialexander28** [comment]
Still not working.  Any guidance?

**Comment by khmurovich** [comment]
@ialexander26 probably it is only red highlighting, not error.

**Comment by ialexander28** [comment]
Ok, so just let it run in red text until completion.

**Comment by ialexander28** [comment]
Still not working

![image](https://user-images.githubusercontent.com/29103853/41672551-69e95ed2-7477-11e8-9f73-5ae5083d057c.png)

**Comment by subbaraok** [comment]
@ialexander26 

Please see if the below comments will help resolve the issue. I was not sure on your comment and hence I am giving the detailed steps. My apologies if you think the level of detail was NOT needed.
 
In  the same directory where you ran the build_mac command, go to the "web" folder using command "cd web"
make a copy of the file "package.json" and this copy can be used to overwite if issue is not resolved 
use your favourite editor to edit the file package.json with the 2 changes as below:
change #1 update L#15 
from
    "build:webpack": "cross-env NODE_ENV=production babel-node ./tools/build",
to 
    "build:webpack": "cross-env NODE_ENV=production&& babel-node ./tools/build",
	
change #2 Update L#17 from
    "serve": "cross-env NODE_ENV=production node ./bin/server",
to
    "serve": "cross-env NODE_ENV=production&& node ./bin/server",

save the file

go back to the main folder and then rerun the same command of ./build_mac.sh

After command execution completes, check to see if the issue is resolved.

**Comment by ialexander26** [comment]
Thanks. Tried the changes and still getting the same error: 
![image](https://user-images.githubusercontent.com/15055888/41736251-2940ca5a-7549-11e8-944c-d189e119afb0.png)

**Comment by Paullaw102** [comment]
Could you clarify your develop responsibilities?version and packages pls.

**Comment by ialexander26** [comment]
@ljbennett62 
Thanks for your help!  I was finally able to re-install the packages and run the Dapp.
